export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PURCHESABLE = "UPDATE_PURCHESABLE";
export const RESET_INGREDIENT = "RESET_INGREDIENT";
